<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'post_count', 'created'];

    const CREATED_AT = 'created';

    public $timestamps = false;

    protected $dates = [self::CREATED_AT];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Category $category) {
            $category->{self::CREATED_AT} = new Carbon();
        });

        self::deleting(function (Category $category) {
            $category->posts()->delete();
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}
